[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.13.0"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/airshipit/shared_invite/zt-cr7kp0bp-6lVDPPK~Cn2Ln7HPCmTTIw"
  status = 302