[build]
  command = "yarn site:build"
  publish = "site/.vuepress/dist/"
[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/airshipit/shared_invite/zt-cr7kp0bp-6lVDPPK~Cn2Ln7HPCmTTIw"
  status = 302
